# Generated by Django 4.1.5 on 2023-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
