# Generated by Django 4.1.5 on 2023-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_post_author_alter_cuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ghost_fio',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='ФИО'),
        ),
    ]
