# Generated by Django 4.1.5 on 2023-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_post_ghost_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ghost_fio',
            field=models.CharField(default=2, max_length=70, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
